name: My second
on: [push]
jobs:
run-python:
run-on: ubuntu-latest
steps:
-name: checkout repository
uses: action/checkout@v3
-name: setup Python
uses: action/setup-python@v4
-name: run python script
run: pytho even.py

