name: Run python2
on: [push]
jobs:
  run-python:
  runs-on: ubuntu-latest
  steps:
    -name: checkout repository
     uses:  actions/checkout@v3
    -name:  setup-python
     uses:  actions/setup-Python@v4
    -name:  Run python script
      run:  python even.py
        


